### ISSUE TITLE
Fifo Queues

### ISSUE THREAD

**Issue by eyal-stratoscale** [iain/fake_sqs#49] opened 2017-01-11 12:34 UTC
Hey

Is there any intention to implement FIFO queues?

Cheers

**Comment by elliotchance** [comment] 2017-03-22 06:32
#48

**Comment by tiwilliam** [comment] 2017-07-21 22:54
Duplicate of #48.

**Closed by tiwilliam** 2017-07-21 22:54 UTC

**Comment by mahngiel** [comment] 2017-07-26 17:13
@tiwilliam 
How can this be a duplicate of #48 when that issue is a duplicate of THIS issue? recursion, mate.
