### ISSUE TITLE
I get a 500 with this stack trace when I try to GetQueueAttributes 

### ISSUE THREAD

**Issue by DocMerlin** [iain/fake_sqs#39] opened 2016-03-10 16:23 UTC
I get a 500 with this stack trace when I try to GetQueueAttributes 

```
2016-03-10 10:20:23 - ArgumentError - wrong number of arguments (1 for 2):
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/actions/get_queue_attributes.rb:11:in `call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/api.rb:39:in `block in call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/queues.rb:48:in `block in transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/memory_database.rb:21:in `block in transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/memory_database.rb:20:in `synchronize'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/memory_database.rb:20:in `transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/queues.rb:47:in `transaction'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/api.rb:38:in `call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/web_interface.rb:39:in `block in <class:WebInterface>'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/show_output.rb:13:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /Library/Ruby/Gems/2.0.0/gems/fake_sqs-0.3.1/lib/fake_sqs/catch_errors.rb:12:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
    /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
    /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
127.0.0.1 - - [10/Mar/2016:10:20:23 -0600] "POST / HTTP/1.1" 500 - 0.0215
```

**Comment by tiwilliam** [comment] 2017-07-22 00:27
Duplicate of #25.

**Closed by tiwilliam** 2017-07-22 00:27 UTC
